export const transcript = [
    {time: {start:0, end:0}, text: `[Música]`},
    {time: {start:0, end:2}, text: `Obrigado Murilo e bem obrigado lua harte`},
    {time: {start:0, end:6}, text: `Obrigado dicas 87 87 foi o ano do`},
    {time: {start:0, end:8}, text: `terceiro casamento dele agradece também`},
    {time: {start:0, end:10}, text: `não vai tomar no seu cu pois é meu`},
    {time: {start:0, end:11}, text: `chapéu Aposto que essa é a primeira Live`},
    {time: {start:0, end:13}, text: `de outubro que vocês estão vendo se não`},
    {time: {start:0, end:15}, text: `for a primeira Live deu tudo na primeira`},
    {time: {start:0, end:16}, text: `Live de punhetaço de outubro né então`},
    {time: {start:0, end:18}, text: `preparem para todos vocês que foram`},
    {time: {start:0, end:20}, text: `fortes até o momento depois da`},
    {time: {start:0, end:21}, text: `Tempestade vem a bonança eu quero eu`},
    {time: {start:0, end:23}, text: `quero ver um tsunami Branco Olha a Live`},
    {time: {start:0, end:25}, text: `do tsunami Branco`},
    {time: {start:0, end:26}, text: `qual que é a consistência a consistência`},
    {time: {start:0, end:29}, text: `da substância não é cremoso é gosmento`},
    {time: {start:0, end:32}, text: `né gosmento espesso pegajoso essa Live`},
    {time: {start:0, end:34}, text: `do tsunami viscoso alguém venceu o novo`},
    {time: {start:0, end:38}, text: `e quem venceu`},
    {time: {start:0, end:42}, text: `agora dou a bunda não dava para não dava`},
    {time: {start:0, end:44}, text: `para ter prazer pelo Pinto teve que ter`},
    {time: {start:0, end:46}, text: `prazer pelo outro lado batendo agora`},
    {time: {start:0, end:47}, text: `Calma também não é assim que essas bola`},
    {time: {start:0, end:50}, text: `deve tá de azul não é brincadeira então`},
    {time: {start:0, end:51}, text: `aqui é a eleição já foi tá que a gente`},
    {time: {start:0, end:53}, text: `tá no futuro não posso dizer quem venceu`},
    {time: {start:0, end:55}, text: `porque senão a gente gera paradoxo pô`},
    {time: {start:0, end:58}, text: `nossa dá uma treta para Deus que é uma`},
    {time: {start:1, end:0}, text: `loucura depois ele até me processa`},
    {time: {start:1, end:1}, text: `depois seu vazar que ele vai chegar`},
    {time: {start:1, end:3}, text: `marca de novo que nem a morte da`},
    {time: {start:1, end:5}, text: `rainha fiz uma live já sabendo da morte`},
    {time: {start:1, end:6}, text: `da rainha antes de você mas eu tive que`},
    {time: {start:1, end:8}, text: `ficar quieto não falei nada bom prever a`},
    {time: {start:1, end:10}, text: `morte da rainha não era não era ela`},
    {time: {start:1, end:11}, text: `também é grande vantagem né porque era`},
    {time: {start:1, end:12}, text: `só pra olhar pra cara tá aquele rosto`},
    {time: {start:1, end:14}, text: `cada vez assistir Live transando`},
    {time: {start:1, end:20}, text: `vem aqui amor vem aqui ele tá lá não`},
    {time: {start:1, end:22}, text: `deixa eu comentar aqui na live do banco`},
    {time: {start:1, end:23}, text: `9:10, da manhã O cara já está neste`},
    {time: {start:1, end:26}, text: `momento estou fazendo sexo virtual com a`},
    {time: {start:1, end:28}, text: `minha namorada e você junto bom aí até`},
    {time: {start:1, end:29}, text: `posso acreditar agora a chance da`},
    {time: {start:1, end:31}, text: `namorada dele ser outro maluco pegando a`},
    {time: {start:1, end:33}, text: `primeira Live tô muito feliz`},
    {time: {start:1, end:35}, text: `eu nem tanto com a sua presença até sem`},
    {time: {start:1, end:38}, text: `você assim você chegou já senti um clima`},
    {time: {start:1, end:40}, text: `ficando meio pesado pensei Nossa o que`},
    {time: {start:1, end:41}, text: `que será que foi isso aí eu fui ver a`},
    {time: {start:1, end:43}, text: `esse maluco aqui primeira vez deixa eu`},
    {time: {start:1, end:45}, text: `dar uma sentada legal aqui ver se tem`},
    {time: {start:1, end:47}, text: `uma`},
    {time: {start:1, end:51}, text: `pleno 2022 ano da Copa ano da tecnologia`},
    {time: {start:1, end:53}, text: `estamos de eleição o cara ver como é que`},
    {time: {start:1, end:56}, text: `você veio falar de a vida é mais`},
    {time: {start:1, end:57}, text: `do que olha os peixe aqui nossa`},
    {time: {start:1, end:59}, text: `mas olha só ele já tá ele já sabe`},
    {time: {start:2, end:0}, text: `desistindo dele eles tiram tudo né`},
    {time: {start:2, end:2}, text: `enquanto ele não tá sendo comida ele tá`},
    {time: {start:2, end:4}, text: `servindo de decoração`},
    {time: {start:2, end:5}, text: `concordo acho que o peixe tem que se`},
    {time: {start:2, end:7}, text: `mesmo que ninguém fala tá mas`},
    {time: {start:2, end:9}, text: `peixe é tudo peixe nem é gente se você`},
    {time: {start:2, end:10}, text: `fosse um peixe você seria Qual é o tal`},
    {time: {start:2, end:12}, text: `do piano ali olha só sem poder nenhuma`},
    {time: {start:2, end:15}, text: `foto Nada melhor do que uma foto de`},
    {time: {start:2, end:18}, text: `cobra né no beco seria um bom lagarto`},
    {time: {start:2, end:24}, text: `tem uma amostra grátis aqui para você`},
    {time: {start:2, end:26}, text: `dar uma apertadinha nele ver se é bom`},
    {time: {start:2, end:27}, text: `mesmo vê se vale a pena mesmo esse aqui`},
    {time: {start:2, end:29}, text: `é bom esse aqui é bem macio ele tá com`},
    {time: {start:2, end:31}, text: `desconto hein Por que que ele tá com`},
    {time: {start:2, end:32}, text: `desconto O que que significa ele nos`},
    {time: {start:2, end:34}, text: `atendentes tentando fazer Live aqui eles`},
    {time: {start:2, end:37}, text: `vão comemorando quando alguém pega`},
    {time: {start:2, end:38}, text: `quando alguém pega um bicho exatamente`},
    {time: {start:2, end:40}, text: `fica comemorando um peixe banana velho`},
    {time: {start:2, end:42}, text: `tentando pegar isso porque é uma`},
    {time: {start:2, end:44}, text: `vergonha chega a ser até uma vergonha`},
    {time: {start:2, end:45}, text: `alguém achar que eu tenho um mau gosto`},
    {time: {start:2, end:48}, text: `Nossa Senhora`},
    {time: {start:3, end:57}, text: `esse corte da comunidade`},
    {time: {start:3, end:59}, text: `exclamação de história`},
    {time: {start:4, end:2}, text: `já postou uma foto dele com jukes do`},
    {time: {start:4, end:4}, text: `nada a sua Martinho eu tinha posto uma`},
    {time: {start:4, end:7}, text: `foto de uma com a minha mãe eu falei que`},
    {time: {start:4, end:8}, text: `é essa magia safado eu tô até`},
    {time: {start:4, end:11}, text: `agora sem entender a primeira Live tô`},
    {time: {start:4, end:12}, text: `amando se Jura por Deus tá manda essa`},
    {time: {start:4, end:14}, text: `merda aí ó olha`},
    {time: {start:4, end:19}, text: `Ai que filha da`},
    {time: {start:4, end:22}, text: `adolescente no Japão já nasce com 40`},
    {time: {start:4, end:25}, text: `todos mano eu terminei com a namorada ih`},
    {time: {start:4, end:28}, text: `cara nossa eu não tô sentindo minha`},
    {time: {start:4, end:29}, text: `perna direita filho acho que ele cruzou`},
    {time: {start:4, end:31}, text: `a gente fala como faz para ser estranho`},
    {time: {start:4, end:32}, text: `igual a você Ah não é do dia pra noite`},
    {time: {start:4, end:35}, text: `não tem gente que tem talvez até mais um`},
    {time: {start:4, end:37}, text: `mas leva tempo leva tempo para`},
    {time: {start:4, end:39}, text: `masterizar que já tá em qual nível`},
    {time: {start:4, end:43}, text: `Tá mesmo falando português no Japão`},
    {time: {start:4, end:46}, text: `cometendo crime tá porque não pode ser`},
    {time: {start:4, end:48}, text: `sabe né não guarda me pega fazendo uma`},
    {time: {start:4, end:50}, text: `loucura dessa aqui filho é cinco anos`},
    {time: {start:4, end:52}, text: `vendo o sol nascer quadrado`},
    {time: {start:4, end:55}, text: `Sol Nascente se o sol vai nascer`},
    {time: {start:4, end:57}, text: `quadrado`},
    {time: {start:5, end:3}, text: `eu ponho a cabeça entre as pernas os`},
    {time: {start:5, end:5}, text: `cara bafo peito o cara peida na latinha`},
    {time: {start:5, end:7}, text: `de Coca Zero depois bafo não pesa pesa`},
    {time: {start:5, end:11}, text: `sim você nunca viu aquela parada lá`},
    {time: {start:5, end:12}, text: `quando quando a gente morre a gente`},
    {time: {start:5, end:13}, text: `perde 21 Gramas 21 G é o último peido 21`},
    {time: {start:5, end:17}, text: `quilos o cara morre perde 21 kg em`},
    {time: {start:5, end:22}, text: `Portugal a gente fala`},
    {time: {start:5, end:24}, text: `dar o peido Mestre quando alguém falece`},
    {time: {start:5, end:27}, text: `em Minas você não vai acreditar quem que`},
    {time: {start:5, end:28}, text: `deu feio do mestre Manuel pergunta desse`},
    {time: {start:5, end:30}, text: `jeito aqui comes e bebes aqui em`},
    {time: {start:5, end:32}, text: `Portugal ela dá o Pedro Mendes foi de`},
    {time: {start:5, end:33}, text: `peidos e Mestres só que eu quero`},
    {time: {start:5, end:35}, text: `engravidar de ti como faz tem um banco`},
    {time: {start:5, end:36}, text: `de esperma`},
    {time: {start:5, end:38}, text: `ali no Grajaú Teve uma época que eu tava`},
    {time: {start:5, end:40}, text: `precisando de uma graninha eu acabei`},
    {time: {start:5, end:43}, text: `fazendo uma doação ali mano que isso`},
    {time: {start:5, end:44}, text: `refrigerante de chupa-chupa nunca vi`},
    {time: {start:5, end:47}, text: `isso aqui não tá coisa nova coisa quente`},
    {time: {start:5, end:48}, text: `só no Japão primeiro no Japão é coreano`},
    {time: {start:5, end:50}, text: `primeiro na floresta você pega a visão`},
    {time: {start:5, end:52}, text: `do mesmo jeito`},
    {time: {start:5, end:53}, text: `que o Japão Coreia tudo a mesma coisa aí`},
    {time: {start:5, end:56}, text: `que entrei na academia para mudar de`},
    {time: {start:5, end:58}, text: `vida e acabei de pegar varío cara ele`},
    {time: {start:6, end:0}, text: `era maior gordão jogava logo falou não`},
    {time: {start:6, end:2}, text: `vou mudar de vida chega chega agora as`},
    {time: {start:6, end:4}, text: `Pulse vem agora as pulseve primeiro que`},
    {time: {start:6, end:6}, text: `ele é academia o cara pegou Varela pelo`},
    {time: {start:6, end:8}, text: `Smart Fitness ficou carregando essa Live`},
    {time: {start:6, end:10}, text: `nas costas tá acontecendo nada na rua se`},
    {time: {start:6, end:12}, text: `não fosse meu humor fabuloso isso aqui`},
    {time: {start:6, end:13}, text: `estava uma bosta tem que testar a`},
    {time: {start:6, end:15}, text: `temperatura né eu não vou poder entrar`},
    {time: {start:6, end:17}, text: `quer dizer se for na testa de boa né`},
    {time: {start:6, end:18}, text: `problema se eles quiserem medir a`},
    {time: {start:6, end:20}, text: `temperatura do meu rabo as máquinas de`},
    {time: {start:6, end:21}, text: `cigarro aqui vamos ver se tem algo que`},
    {time: {start:6, end:22}, text: `eu mais gosto de mascar é esse Neve usa`},
    {time: {start:6, end:25}, text: `aqui`},
    {time: {start:6, end:26}, text: `sem nada engraçado Tentei tirar Tentei`},
    {time: {start:6, end:29}, text: `tirar leite de pedra ali mas não arrumar`},
    {time: {start:6, end:30}, text: `meu cabelinho aqui`},
    {time: {start:6, end:34}, text: `do Fundão eleitoral só se for o meu`},
    {time: {start:6, end:36}, text: `Fundão os cara fez corrupção no meu`},
    {time: {start:6, end:37}, text: `Fundão assim corromperam meu Fundão e`},
    {time: {start:6, end:40}, text: `agora estou com o Fundão corrompido`},
    {time: {start:6, end:44}, text: `deu para ouvir na Live isso que acabou`},
    {time: {start:6, end:46}, text: `de acontecer foi só me`},
    {time: {start:6, end:47}, text: `disseram passar atrás dele soltou tudo`},
    {time: {start:6, end:50}, text: `ali foi isso aí ó o peidão peidão na`},
    {time: {start:6, end:52}, text: `barriga`},
    {time: {start:6, end:56}, text: `que isso que isso`},
    {time: {start:7, end:8}, text: `Rivaldo`},
    {time: {start:7, end:15}, text: `ronald's`},
    {time: {start:7, end:21}, text: `eu não se importou de ser filmado tá`},
    {time: {start:7, end:23}, text: `ligado mas tipo assim pô mó Bad né se`},
    {time: {start:7, end:25}, text: `ele soubesse que eu já peguei ele`},
    {time: {start:7, end:27}, text: `peidando né mano depois quando ele tiver`},
    {time: {start:7, end:29}, text: `ação Amanhã quando ele tiver ação ele`},
    {time: {start:7, end:31}, text: `vai saber que tem um maluco lá do outro`},
    {time: {start:7, end:32}, text: `lado do mundo que filmou ele peidando`},
    {time: {start:7, end:34}, text: `depois filmou ele caindo depois filmou`},
    {time: {start:7, end:35}, text: `ele falando várias bostas pegou os cara`},
    {time: {start:7, end:37}, text: `logo depois do rodízio ficou assim ele`},
    {time: {start:7, end:40}, text: `de tudo quanto é a cor aqui`},
    {time: {start:7, end:41}, text: `representatividade`},
    {time: {start:7, end:44}, text: `café é esse aqui ó tô até desconfiando`},
    {time: {start:7, end:46}, text: `que não tô vendo nem que seja a festa`},
    {time: {start:7, end:48}, text: `Talvez seja assédio mesmo não é amor`},
    {time: {start:7, end:50}, text: `mesmo`},
    {time: {start:7, end:55}, text: `é engraçado o que que é que vocês estão`},
    {time: {start:7, end:59}, text: `a aqui também não tenho Liberdade Não`},
    {time: {start:8, end:1}, text: `Tem liberdade de expressão aqui nessa`},
    {time: {start:8, end:3}, text: `rua mano muita gente que morreu por nada`},
    {time: {start:8, end:5}, text: `cigarro barlist Nossa deve ser uma dele`},
    {time: {start:8, end:7}, text: `deve fazer um bem pro pulmão entrar`},
    {time: {start:8, end:9}, text: `nesse ambiente ou sax do nada do nada um`},
    {time: {start:8, end:11}, text: `dia maravilhoso bom para reproduzir`},
    {time: {start:8, end:12}, text: `música de sexo aqui olha isso`},
    {time: {start:8, end:19}, text: `os brother se encontra na rua de`},
    {time: {start:8, end:23}, text: `apertou o que está fazendo será que você`},
    {time: {start:8, end:25}, text: `acha que tá fazendo aí o cara tá só os`},
    {time: {start:8, end:27}, text: `frangalho aqui é pior ainda os cara`},
    {time: {start:8, end:29}, text: `fazendo o homem cai no vocês`},
    {time: {start:8, end:30}, text: `sabem que aquilo já apontei essa Cultura`},
    {time: {start:8, end:32}, text: `né que quando o chefe assim nas empresas`},
    {time: {start:8, end:35}, text: `tradicional quando o chefe tem uns dias`},
    {time: {start:8, end:36}, text: `assim que o chefe chama o escritório`},
    {time: {start:8, end:39}, text: `todo para beber é maior falta de`},
    {time: {start:8, end:40}, text: `educação assim se o funcionário não foi`},
    {time: {start:8, end:42}, text: `enquanto o chefe tiver bebendo`},
    {time: {start:8, end:43}, text: `funcionando Tem que beber junto se não é`},
    {time: {start:8, end:45}, text: `falta de respeito pô os caras são loucos`},
    {time: {start:8, end:47}, text: `aí o cara faz um desse no já`},
    {time: {start:8, end:48}, text: `penso não hoje não vai ser de beber não`},
    {time: {start:8, end:50}, text: `hoje é de comer se o chefe chupar`},
    {time: {start:8, end:52}, text: `uma bem gostosa tem que chupar`},
    {time: {start:8, end:54}, text: `também onde mora o chefe é muito`},
    {time: {start:8, end:57}, text: `perigoso para mim namorar sozinho aí sem`},
    {time: {start:8, end:59}, text: `família tem o trauma daquela novela que`},
    {time: {start:9, end:0}, text: `sequestro das mina pra Turquia não é`},
    {time: {start:9, end:2}, text: `perigoso não`},
    {time: {start:9, end:3}, text: `escuta muito caso`},
    {time: {start:9, end:7}, text: `inexplicável eita`},
    {time: {start:9, end:15}, text: `Mas seria um pecado coçar na frente do`},
    {time: {start:9, end:18}, text: `espelho mas aqui tá Escondidinho Será`},
    {time: {start:9, end:19}, text: `que não tem câmera Nossa tô na frente de`},
    {time: {start:9, end:20}, text: `uma câmera coçando o saco velho que`},
    {time: {start:9, end:22}, text: `pariu`},
    {time: {start:9, end:24}, text: `essa mecânica isso aqui`},
    {time: {start:9, end:26}, text: `[Música]`},
    {time: {start:9, end:28}, text: `que rapaz aí a gente tá seguro isso aqui`},
    {time: {start:9, end:32}, text: `é para massagear o rosto`},
    {time: {start:9, end:34}, text: `funciona não funciona o rosto debaixo`},
    {time: {start:9, end:37}, text: `massagear os lábios de baixo Falar o quê`},
    {time: {start:9, end:39}, text: `mano passei por algum espelho Ah isso`},
    {time: {start:9, end:40}, text: `aqui parece um espelho mas é um vidro o`},
    {time: {start:9, end:43}, text: `japa ele tá lá do outro lado porque ele`},
    {time: {start:9, end:45}, text: `tá agachado número corredor também`},
    {time: {start:9, end:47}, text: `no espelho saiu já para achar é que`},
    {time: {start:9, end:50}, text: `vocês estão sem Face eu tô vendo reflexo`},
    {time: {start:9, end:51}, text: `é assim que vocês querem ficar`},
    {time: {start:9, end:52}, text: `maquininha de monstro Inclusive eu já`},
    {time: {start:9, end:55}, text: `tomei de de monster hoje eu já não passo`},
    {time: {start:9, end:57}, text: `num antidoping aqui ingerir pelos anos`},
    {time: {start:9, end:59}, text: `ainda para bater mais rápido já foi`},
    {time: {start:10, end:0}, text: `alguma baladinha festival baladinha mano`},
    {time: {start:10, end:2}, text: `eu tenho 43 anos acho que eu fico`},
    {time: {start:10, end:4}, text: `fazendo essas coisas aí já filmouse`},
    {time: {start:10, end:6}, text: `bacajá operou nunca`},
    {time: {start:10, end:7}, text: `eu deixo afimose pra não pegar resfriado`},
    {time: {start:10, end:9}, text: `se sentiu na mão do palhaço todo dia`},
    {time: {start:10, end:12}, text: `até a bucha de cinco nas biqueira`},
    {time: {start:10, end:17}, text: `ele falou que papinho na escola do`},
    {time: {start:10, end:19}, text: `Japonês tem uma estrutura que eles`},
    {time: {start:10, end:21}, text: `ensinam um dia que é o oculto no dia que`},
    {time: {start:10, end:23}, text: `a professora`},
    {time: {start:10, end:25}, text: `vai ter o cu`},
    {time: {start:10, end:30}, text: `na frente da sala inteira ficou sabendo`},
    {time: {start:10, end:33}, text: `da história`},
    {time: {start:10, end:34}, text: `Faria Lima nós vamos pensar alguma coisa`},
    {time: {start:10, end:36}, text: `engraçada aqui só pra gente falar vai só`},
    {time: {start:10, end:38}, text: `para não ficar um clima fala sobre CL`},
]