export const transcript = [
    {time: {start:1, end:2}, text: `[Música]`},
    {time: {start:3, end:4}, text: `será completamente em espanhol senão`},
    {time: {start:5, end:6}, text: `hablas pode retirar só que você acredita`},
    {time: {start:7, end:8}, text: `em Maradona eu não acredito não para mim`},
    {time: {start:9, end:10}, text: `Maradona e Osama Bin Laden é tudo`},
    {time: {start:11, end:12}, text: `invenção dos Estados Unidos para`},
    {time: {start:13, end:14}, text: `justificar a guerra tem cara de que`},
    {time: {start:15, end:16}, text: `gosta de banda depressiva você gosta de`},
    {time: {start:17, end:18}, text: `rádio`},
    {time: {start:19, end:20}, text: `você deve ser um cara muito feliz nos`},
    {time: {start:21, end:22}, text: `comentários dos meus vídeos tá direto`},
    {time: {start:23, end:24}, text: `Nossa mas esse vídeo é antigo o pessoal`},
    {time: {start:25, end:26}, text: `tá tudo de máscara cara inocente os cara`},
    {time: {start:27, end:28}, text: `subestimam o poder do japonês de usar`},
    {time: {start:29, end:30}, text: `máscara Vocês estão vendo ali o logo`},
    {time: {start:31, end:32}, text: `daquela loja ali é um coração de corno`},
    {time: {start:33, end:34}, text: `um pedaço não vai ter hoje pedaço a`},
    {time: {start:35, end:36}, text: `gente a gente já tentou fazer pedaço uma`},
    {time: {start:37, end:38}, text: `vez todo mundo lembra o que aconteceu e`},
    {time: {start:39, end:40}, text: `a gente teve que sair de ambulância`},
    {time: {start:41, end:42}, text: `disso aqui para aguentar é dois [ __ ] de`},
    {time: {start:43, end:44}, text: `[ __ ]`},
    {time: {start:45, end:46}, text: `Quase que eu filme coisa que não podia`},
    {time: {start:47, end:48}, text: `mas só tem bicho escroto mano parece um`},
    {time: {start:49, end:50}, text: `mendigo é um urso mendigo todo estragado`},
    {time: {start:51, end:52}, text: `parece que tá encardido já tem um curso`},
    {time: {start:53, end:54}, text: `sem fogo hein ele tá sem fogo no rabo Ah`},
    {time: {start:55, end:56}, text: `ele Tower Story 57 Ela assistiu`},
    {time: {start:58, end:59}, text: `a minha postura aqui que tá [ __ ] eu fui`},
    {time: {start:60, end:61}, text: `no médico então ele falou assim você`},
    {time: {start:62, end:63}, text: `precisa fazer RPG eu comecei a jogar`},
    {time: {start:64, end:65}, text: `não melhorou nem um pouco não sei tô até`},
    {time: {start:66, end:67}, text: `agora sem entender`},
    {time: {start:68, end:69}, text: `faça um Sonic ali né Tem um gato duro`},
    {time: {start:70, end:71}, text: `já tá para o abate já mataram já`},
    {time: {start:72, end:73}, text: `penduraram para secar o sangue cadê cadê`},
    {time: {start:74, end:75}, text: `cadê`},
    {time: {start:76, end:77}, text: `[Música]`},
    {time: {start:78, end:79}, text: `o ruim de novo mano vou tentar [ __ ] esse`},
    {time: {start:80, end:81}, text: `aqui que tá na frente Será que ele tá`},
    {time: {start:82, end:83}, text: `travado ele tá de costas eu não consigo`},
    {time: {start:84, end:85}, text: `ver`},
    {time: {start:86, end:87}, text: `ó eu deixei nele tá vendo olha o`},
    {time: {start:88, end:89}, text: `elástico no meio tá parecendo uma bunda`},
    {time: {start:90, end:91}, text: `rosa aqui`},
    {time: {start:92, end:93}, text: `os bonecos mas lembrem sempre de`},
    {time: {start:94, end:95}, text: `plastificar os bonecos hein quando for`},
    {time: {start:96, end:97}, text: `usar eu sempre ficaria com medo de`},
    {time: {start:98, end:99}, text: `comprar a boneca usado assim porque vai`},
    {time: {start:100, end:101}, text: `sabe lá que o cara já fez né em cima de`},
    {time: {start:102, end:103}, text: `um boneco só sabe falar de [ __ ] tá`},
    {time: {start:104, end:105}, text: `vamos falar de de [ __ ] Então meninas`},
    {time: {start:106, end:107}, text: `um passo à frente`},
    {time: {start:108, end:109}, text: `e cara`},
    {time: {start:110, end:111}, text: `A loja inteira é mais de 112 vai ter 113`},
    {time: {start:114, end:115}, text: `mano Ai Que [ __ ] é essa`},
    {time: {start:116, end:117}, text: `Que [ __ ] é essa que que tá acontecendo`},
    {time: {start:118, end:119}, text: `o shopping inteiro é mais 120 Agora não`},
    {time: {start:121, end:122}, text: `dá mais aqui por fora você já consegue`},
    {time: {start:123, end:124}, text: `ter uma ideia o que que acontece lá`},
    {time: {start:125, end:126}, text: `dentro aqui elas ainda estão com roupa`},
    {time: {start:127, end:128}, text: `[Música]`},
    {time: {start:129, end:130}, text: `lá dentro não tem como descer mas só tem`},
    {time: {start:131, end:132}, text: `esse cara para subir não tem jeito vou`},
    {time: {start:133, end:134}, text: `ter que continuar subindo agora elevador`},
    {time: {start:135, end:136}, text: `não quero pegar não tenho medo de`},
    {time: {start:137, end:138}, text: `elevador maluco tá tendo um AVC os`},
    {time: {start:139, end:140}, text: `maluco Ah lá o maluco fazendo cabedão`},
    {time: {start:141, end:142}, text: `você sabe que o nome desse bagulho aqui`},
    {time: {start:143, end:144}, text: `é cabedona o cara põe a mão assim na`},
    {time: {start:145, end:146}, text: `mina assim na parede aí o outro aqui na`},
    {time: {start:147, end:148}, text: `frente ele tá tendo um AVC ó ninguém tá`},
    {time: {start:149, end:150}, text: `nem aí tá com funcionando ali pô tá`},
    {time: {start:151, end:152}, text: `postando cortando Lacoste que já fez`},
    {time: {start:153, end:154}, text: `isso já fizeram comigo chegou em mim`},
    {time: {start:155, end:156}, text: `assim me botou na parede`},
    {time: {start:157, end:158}, text: `acelera aqui para você pintar o seu você`},
    {time: {start:159, end:160}, text: `tentar com meu pinto os cara compra o`},
    {time: {start:161, end:162}, text: `cana tudo Brancão E aí Você pinta ele`},
    {time: {start:163, end:164}, text: `olha fazendo joinha fazendo maior burro`},
    {time: {start:165, end:166}, text: `eles compram Será que é verdade você`},
    {time: {start:167, end:168}, text: `realmente gosta de fazer sexo não pô`},
    {time: {start:169, end:170}, text: `tanto você tirou um bagulho desse filho`},
    {time: {start:171, end:172}, text: `morrer`},
    {time: {start:173, end:174}, text: `no Japão tem mesmo né Tem uma lei`},
    {time: {start:175, end:176}, text: `que obriga os prédios foi uma certa`},
    {time: {start:177, end:178}, text: `quantidade de prédios a ter uma área`},
    {time: {start:179, end:180}, text: `verde no terraço Por isso que às vezes a`},
    {time: {start:181, end:182}, text: `gente sobe nos prédios tem uns prédios`},
    {time: {start:183, end:184}, text: `cabeludo cheio de grama do Terraço Olha`},
    {time: {start:185, end:186}, text: `que baguncinha nesse Terraço`},
    {time: {start:187, end:188}, text: `aí do outro lado não é já Osasco`},
    {time: {start:189, end:190}, text: `trabalhou a vida inteira agora o único`},
    {time: {start:191, end:192}, text: `lazer dela cuidar das plantinhas do`},
    {time: {start:193, end:194}, text: `Terraço se não vai atrapalhar minha`},
    {time: {start:195, end:196}, text: `performance`},
    {time: {start:197, end:198}, text: `eu ia até sem voz não foi um gênio foi o`},
    {time: {start:199, end:200}, text: `último suspiro fumante com peso japonês`},
    {time: {start:201, end:202}, text: `já usava O Máscara antes da pandemia`},
    {time: {start:203, end:204}, text: `agora ficou a pandemia esquece o próximo`},
    {time: {start:205, end:206}, text: `207 anos você não sai na rua sem máscara`},
    {time: {start:208, end:209}, text: `girar e já usava a máscara antes de`},
    {time: {start:210, end:211}, text: `Cristo girar e já usava a máscara a`},
    {time: {start:212, end:213}, text: `feiticeira já usava bastante`},
    {time: {start:214, end:215}, text: `difícil mas 0216`},
    {time: {start:217, end:218}, text: `eu não consigo largar esse pau duro tô`},
    {time: {start:219, end:220}, text: `tentando abaixar meu pau já faz exame`},
    {time: {start:221, end:222}, text: `fez eu vou no médico Qual que é o`},
    {time: {start:223, end:224}, text: `contrário de um Viagra tem algum remédio`},
    {time: {start:225, end:226}, text: `para brochar`},
    {time: {start:227, end:228}, text: `os cara os cara fala não da hora Palma`},
    {time: {start:229, end:230}, text: `ninguém vê o lado dele o maluco tá`},
    {time: {start:231, end:232}, text: `sempre Brochado já fazem 233 anos cabeça`},
    {time: {start:234, end:235}, text: `do encrosada já tá roxo já mas ele é`},
    {time: {start:236, end:237}, text: `guerreiro o a bosta de vocês é tipo kibe`},
    {time: {start:238, end:239}, text: `ou é tipo churros né a garra de três tá`},
    {time: {start:240, end:241}, text: `presta atenção nisso aqui`},
    {time: {start:242, end:243}, text: `presta atenção nisso aqui de primeira tá`},
    {time: {start:244, end:245}, text: `de primeira tá de primeira`},
    {time: {start:246, end:247}, text: `e descendo subindo e descendo todo mundo`},
    {time: {start:248, end:249}, text: `que comprou VR e usa para assistir pornô`},
    {time: {start:250, end:251}, text: `né não é possível alguém que tem BR aí`},
    {time: {start:252, end:253}, text: `pode confirmar nossa cadeira Gamer essa`},
    {time: {start:254, end:255}, text: `daqui é para zirlanda City mas daí não`},
    {time: {start:256, end:257}, text: `dá ou tem que andar ela tem que sentar`},
    {time: {start:258, end:259}, text: `eu já perdi o meu o meu senso ético há`},
    {time: {start:260, end:261}, text: `muito tempo hoje eu só me importo com`},
    {time: {start:262, end:263}, text: `entretenimento`},
    {time: {start:264, end:265}, text: `aqui ainda estão de boa 266.267 268.269`},
    {time: {start:270, end:271}, text: `olha ali olha aqui 272.273`},
    {time: {start:274, end:275}, text: `ienes esse [ __ ] o fone aqui 276 Alguém`},
    {time: {start:277, end:278}, text: `conversa e você olha assim você nem dá`},
    {time: {start:279, end:280}, text: `nada dois mil reais eu já vi piores já`},
    {time: {start:281, end:282}, text: `que eles ainda estão ali para você pegar`},
    {time: {start:283, end:284}, text: `imagina se fica na prateleira Olha isso`},
    {time: {start:285, end:286}, text: `aqui`},
    {time: {start:287, end:288}, text: `tá [ __ ] filho que [ __ ] é essa mano`},
    {time: {start:289, end:290}, text: `[ __ ] é o fone mais caro do mundo`},
    {time: {start:291, end:292}, text: `293.294`},
    {time: {start:295, end:296}, text: `iene 297 mil reais`},
    {time: {start:298, end:299}, text: `a canção dos Anjos é aquele bagulho do`},
    {time: {start:300, end:301}, text: `BioShock mano a mulher tá metendo`},
    {time: {start:302, end:303}, text: `metendo o Chase ali mesmo as vendedora`},
    {time: {start:304, end:305}, text: `de piano Elas têm que saber tocar né`},
    {time: {start:306, end:307}, text: `Elas têm que manjar do instrumento toca`},
    {time: {start:308, end:309}, text: `alguma coisa ba eu sempre fui punhetista`},
    {time: {start:310, end:311}, text: `da minha banda ninguém toca uma [ __ ]`},
    {time: {start:312, end:313}, text: `que nem lógica essa piada ia acontecer`},
    {time: {start:314, end:315}, text: `lógico eu só toca o terror Tá tudo`},
    {time: {start:316, end:317}, text: `desligado [ __ ] eu ia tocar um Beethoven`},
    {time: {start:318, end:319}, text: `aqui mas ninguém quer não isso aqui tá`},
    {time: {start:320, end:321}, text: `ligado aqui ó presta atenção nisso aqui`},
    {time: {start:322, end:323}, text: `Saudade desse caminhão de guerra linda`},
    {time: {start:324, end:325}, text: `nota da com medo de causar muito aqui`},
    {time: {start:326, end:327}, text: `[Música]`},
    {time: {start:328, end:329}, text: `eu errei que o negócio é mais bacon`},
    {time: {start:330, end:331}, text: `mesmo aqui ó tem até o espelho para você`},
    {time: {start:332, end:333}, text: `ver se você fica bem com o fonezinho`},
    {time: {start:334, end:335}, text: `você compra o fone de 336.337 yenes e`},
    {time: {start:338, end:339}, text: `ele não combina com seu drible`},
    {time: {start:340, end:341}, text: `é porque tá de dia Como é que você sabe`},
    {time: {start:342, end:343}, text: `tá de dia eu tô dentro de uma loja e não`},
    {time: {start:344, end:345}, text: `sabe nem fazer piada hein Olha esse`},
    {time: {start:346, end:347}, text: `Pikachu toda deep web aqui mano que isso`},
    {time: {start:348, end:349}, text: `Olha isso os caras isso aqui significa`},
    {time: {start:350, end:351}, text: `alguma coisa é o dito virado em Pikachu`},
    {time: {start:352, end:353}, text: `alguma coisa assim porque não é possível`},
    {time: {start:354, end:355}, text: `Ele tá muito feio acho que depois do`},
    {time: {start:356, end:357}, text: `prensado de dois pontos fica a Ju depois`},
    {time: {start:358, end:359}, text: `digitar a Deus com D minúsculo`},
    {time: {start:360, end:361}, text: `o moleque correu de mim`},
    {time: {start:362, end:363}, text: `é um planeta isso aqui Cala a boca fala`},
    {time: {start:364, end:365}, text: `o bagulho para impressão digital ó tô`},
    {time: {start:366, end:367}, text: `desvenda crime Departamento de Polícia`},
    {time: {start:368, end:369}, text: `Vem aqui para comprar não gosto de`},
    {time: {start:370, end:371}, text: `criança mas gosta de fazer né`},
    {time: {start:372, end:373}, text: `não coloque palavras na minha boca que`},
    {time: {start:374, end:375}, text: `eu gosto de transar [ __ ] vou perder`},
    {time: {start:376, end:377}, text: `metade da minha audiência`},
    {time: {start:378, end:379}, text: `já é bonita é você né você que é bonito`},
    {time: {start:380, end:381}, text: `Se fosse você lá na série Nossa tá`},
    {time: {start:382, end:383}, text: `bombando aquilo então vocês vê né que é`},
    {time: {start:384, end:385}, text: `o preconceito aqui olha isso aqui tudo`},
    {time: {start:386, end:387}, text: `PlayStation ali do outro lado é tudo`},
    {time: {start:388, end:389}, text: `Nintendo Switch né e tem dois Bagulho só`},
    {time: {start:390, end:391}, text: `do Xbox aqui ó aqui O Exterminador do`},
    {time: {start:392, end:393}, text: `Kuduro [ __ ] Nem tinha visto`},
    {time: {start:394, end:395}, text: `[Música]`},
    {time: {start:396, end:397}, text: `muito tarde ali Tarde demais já tinha`},
    {time: {start:398, end:399}, text: `tocado aqui ó podia ter um jogo dele`},
    {time: {start:400, end:401}, text: `travado de craque né Aí eu dava valor o`},
    {time: {start:402, end:403}, text: `Leôncio aqui o Leôncio Leôncio da bola`},
    {time: {start:404, end:405}, text: `azul ele participou ele venceu na oferta`},
    {time: {start:406, end:407}, text: `ficou desse jeito aqui`},
    {time: {start:408, end:409}, text: `mano afiador de faca compacto com`},
    {time: {start:410, end:411}, text: `ventosa Que [ __ ] é essa`},
    {time: {start:412, end:413}, text: `criatura de cutilhos compactor Ai Que`},
    {time: {start:414, end:415}, text: `coisinha que bagulho gostoso aqui ó`},
    {time: {start:416, end:417}, text: `bem na hora que Colombo aqui do meu lado`},
    {time: {start:418, end:419}, text: `Ele olhou para mim mas o segredo o`},
    {time: {start:420, end:421}, text: `segredo para você não passar vergonha`},
    {time: {start:422, end:423}, text: `você nunca olhar no olho nos olhos das`},
    {time: {start:424, end:425}, text: `pessoas o que que isso aqui mano o gato`},
    {time: {start:426, end:427}, text: `acende no charuto aqui vamos ali na loja`},
    {time: {start:428, end:429}, text: `de disco ali que eu tô atrás de um do`},
    {time: {start:430, end:431}, text: `Zeca Pagodinho e um do Claudinho e`},
    {time: {start:432, end:433}, text: `[ __ ] será que eles têm perguntar pra`},
    {time: {start:434, end:435}, text: `tendência tipo assim Claudinho e [ __ ]`},
    {time: {start:436, end:437}, text: `Claudinho é [ __ ] Claudinho e [ __ ]`},
    {time: {start:438, end:439}, text: `claudinhos Será que tem ali no brega`},
    {time: {start:440, end:441}, text: `aqui`},
    {time: {start:442, end:443}, text: `eu não posso ver essas coisas que eu já`},
    {time: {start:444, end:445}, text: `fico de pau duro já mas quando quase`},
    {time: {start:446, end:447}, text: `morreu o mundo vai parar ou não ele não`},
    {time: {start:448, end:449}, text: `aprendeu nada com os anos de vida dele`},
    {time: {start:450, end:451}, text: `ele segue desde os 452 ele tá na mesma`},
    {time: {start:453, end:454}, text: `vibe ele sabe que eu ainda vou morrer`},
    {time: {start:455, end:456}, text: `antes do Waze eu ainda vou morrer antes`},
    {time: {start:457, end:458}, text: `do Silvio Santos na verdade`},
    {time: {start:459, end:460}, text: `para quem não sabe inglês são os garotos`},
    {time: {start:461, end:462}, text: `[ __ ] tá esse cara tá alimentando o chat`},
    {time: {start:463, end:464}, text: `que bonitinho Alcione aqui quem que`},
    {time: {start:465, end:466}, text: `perguntou se tinha o senhor`},
    {time: {start:467, end:468}, text: `do Japão é assim olha a Marily japonesa`},
    {time: {start:469, end:470}, text: `mas saindo aqui eu já vou mostrar os`},
    {time: {start:471, end:472}, text: `bagulho que eu roubei entre eles já vou`},
    {time: {start:473, end:474}, text: `dar uma dica tá o fone de 475.476 é`},
    {time: {start:477, end:478}, text: `então na Live Vocês nem percebe né que`},
    {time: {start:479, end:480}, text: `eu tô passando a mão roubei até um`},
    {time: {start:481, end:482}, text: `teclado nas costas aqui os cara nem viu`},
    {time: {start:483, end:484}, text: `Tá tudo no meu cu né meu cu ele é tipo`},
    {time: {start:485, end:486}, text: `aquele saco da mione lá meu cu é tipo o`},
    {time: {start:487, end:488}, text: `saco dele pô não dá para dizer que eu`},
    {time: {start:489, end:490}, text: `não tenho nenhum Tostão furado isso não`},
    {time: {start:491, end:492}, text: `dá pra dizer um triângulo comestível aí`},
    {time: {start:493, end:494}, text: `o triângulo comestível bom aqui vou dar`},
    {time: {start:495, end:496}, text: `uns papo tá bom Aqui tudo na maionese né`},
    {time: {start:497, end:498}, text: `o padrão tanto que é o que mais tem`},
    {time: {start:499, end:500}, text: `aqueles mais fazem mais ou menos aqui do`},
    {time: {start:501, end:502}, text: `nosso eu não recomendo`},
    {time: {start:503, end:504}, text: `o melhor amigo Seven comida Illuminati`},
    {time: {start:505, end:506}, text: `se não for agora também`},
    {time: {start:507, end:508}, text: `se não for agora você está de`},
    {time: {start:509, end:510}, text: `brincadeira Olha isso olha aqui como ele`},
    {time: {start:511, end:512}, text: `já tá toda amassadão Será que o pessoal`},
    {time: {start:513, end:514}, text: `gosta dele mano será que ele é o que`},
    {time: {start:515, end:516}, text: `todo mundo quer pegar ou não`},
    {time: {start:517, end:518}, text: `é agora vocês estão preparados por esse`},
    {time: {start:519, end:520}, text: `momento ele não vai se repetir não`},
    {time: {start:521, end:522}, text: `[Música]`},
    {time: {start:523, end:524}, text: `foi difícil a jornada Foi Difícil`},
    {time: {start:525, end:526}, text: `isso aqui é um pequeno passo para um`},
    {time: {start:527, end:528}, text: `homem um grande passo`},
    {time: {start:529, end:530}, text: `para a humanidade`},
    {time: {start:531, end:532}, text: `mano esse bagulho aqui que tem a loja de`},
    {time: {start:533, end:534}, text: `tenda aqui será que eu tava muito bom`},
    {time: {start:535, end:536}, text: `[Música]`},
    {time: {start:537, end:538}, text: `vocês querem passar pelo inferno só para`},
    {time: {start:539, end:540}, text: `ver você que tem dúvida aí se vocês`},
    {time: {start:541, end:542}, text: `estão aí vocês são pescador mas vocês`},
    {time: {start:543, end:544}, text: `ainda tem salvação e tal eu vou mostrar`},
    {time: {start:545, end:546}, text: `para vocês como é que é o inferno eu não`},
    {time: {start:547, end:548}, text: `vou querer viver até a idade disso aqui`},
    {time: {start:549, end:550}, text: `Silva de lição Esse aí que é o assunto`},
    {time: {start:551, end:552}, text: `filho da Marta Suplicy`},
    {time: {start:553, end:554}, text: `quase que não teve jeito a gente teve`},
    {time: {start:555, end:556}, text: `que se comer tinha do lado esquerdo Ah`},
    {time: {start:557, end:558}, text: `sou eu que tô aqui ó enquanto eu vou`},
    {time: {start:559, end:560}, text: `andando aqui eu vou fazendo mil linha`},
    {time: {start:561, end:562}, text: `aqui para não perder o maxilar`},
    {time: {start:563, end:564}, text: `não se a Caroline já tá entrando nesta`},
    {time: {start:565, end:566}, text: `vida`},
    {time: {start:567, end:568}, text: `meu parceiro tudo bem`},
]